services:
  db:
    image: docker.io/library/postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWD}
      POSTGRES_DB: ${DB}
    volumes:
      - pgdata:/var/lib/postgresql
  # web:
  #   build: .
  #   restart: always
  #   environment:
  #     DATABASE_URL: ${DATABASE_URL}
  #     NODE_ENV: ${NODE_ENV}
  #   ports:
  #     - 3000:3000
  #   depends_on:
  #     - db
volumes:
  pgdata:
